language: C++
dist: xenial
install:
  - sudo apt-get —no-install-recommends -y install cxxtest
script:
  - make
  - make test
  - git ls-files src/ | xargs clang-format -i && git diff —exit-code
  - git ls-files test/ | xargs clang-format -i && git diff —exit-code
